### ISSUE TITLE
deprecated commands

### ISSUE THREAD

**Issue by bhupi-cloudeq** [zweitag/github-actions#43]
Hi

Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Please fix this in your repo.

**Comment by tbho** [comment]
Hi @bhupi-cloudeq,

sorry for my late answer. We updated the action, the warnings should be gone. Thanks for the reminder.

Greetings 

Tobi
